#ifndef BOOST_INCLUDE_WRAPPER_H
#define BOOST_INCLUDE_WRAPPER_H

#ifndef AR_BOOST_FOLDER_NAMESPACE
  #define AR_BOOST_FOLDER_NAMESPACE boost_namespace_folder_undefined
#endif

#define BOOST_INCLUDE(path) <AR_BOOST_FOLDER_NAMESPACE/path>

#endif // BOOST_INCLUDE_WRAPPER_H