#ifndef BOOST_INCLUDE_WRAPPER_H
#define BOOST_INCLUDE_WRAPPER_H

#ifndef BOOST_NAMESPACE
  #define BOOST_NAMESPACE boost
#endif

#define BOOST_INCLUDE(path) <BOOST_NAMESPACE/path>

#endif // BOOST_INCLUDE_WRAPPER_H