#ifndef AR_CACHEDRESOLVER_DEBUGCODES_H
#define AR_CACHEDRESOLVER_DEBUGCODES_H

#include <pxr/pxr.h>
#include "pxr/base/tf/debug.h"

PXR_NAMESPACE_OPEN_SCOPE

TF_DEBUG_CODES(
    CACHEDRESOLVER_RESOLVER,
    CACHEDRESOLVER_RESOLVER_CONTEXT
);

PXR_NAMESPACE_CLOSE_SCOPE

#endif // AR_CACHEDRESOLVER_DEBUGCODES_H