#ifndef AR_FILERESOLVER_DEBUGCODES_H
#define AR_FILERESOLVER_DEBUGCODES_H

#include <pxr/pxr.h>
#include "pxr/base/tf/debug.h"

PXR_NAMESPACE_OPEN_SCOPE

TF_DEBUG_CODES(
    FILERESOLVER_RESOLVER,
    FILERESOLVER_RESOLVER_CONTEXT
);

PXR_NAMESPACE_CLOSE_SCOPE


#endif // AR_FILERESOLVER_DEBUGCODES_H